apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-cdc-config
  labels:
    app: myapp-cdc
data:
  SERVER_ID: "200"
  POSITION_FILE: "/app/storage/binlog_position.json"
  POST_URL: "http://localhost:8080"
  TABLE_GROUPS_FILE: "/app/config/table_groups.yaml"
  REDIS_ADDR: "localhost:6379"
  REDIS_DB: "0"
