apiVersion: v1
kind: Secret
metadata:
  name: myapp-cdc-secret
  labels:
    app: myapp-cdc
type: Opaque
stringData:
  DB_ADDR: "127.0.0.1:3306"
  DB_USER: "root"
  DB_PASSWORD: ""
  DB_FLAVOR: "mysql"
  REDIS_PASSWORD: ""
